#!/usr/bin/bash
#
# ufetch-aux - tiny system info for aux

## INFO
# NOTE: you should have bash installed, and you should modify
#       the path appropriately.

# user is already defined
host="$(hostname)"
os="$(uname -sr)"
kernel="$(uname -v)"
uptime="$(uptime | awk '{print "Up "$3" "$4}'|tr -d ,)"
# A/UX doesn't have these
#packages="$(ls -d /var/db/pkg/* | wc -l | sed -e 's/^[ \t]*//')"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE:'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE:'
		WM="${DESKTOP_SESSION}"
	elif [ -f "${HOME}/.xinitrc" ]; then
		envtype='WM:'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM:'
fi

## No colors, cos A/UX's tput can't do that.
#DEFINE COLORS
# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
#	black="$(tput setaf 0)"
#	red="$(tput setaf 1)"
#	green="$(tput setaf 2)"
#	yellow="$(tput setaf 3)"
#	blue="$(tput setaf 4)"
#	magenta="$(tput setaf 5)"
#	cyan="$(tput setaf 6)"
#	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}"		# labels
nc="${reset}"               # not labels
#nc="${reset}${bold}${yellow}"		# user and hostname
#ic="${reset}${bold}${white}"		# info
#c0="${reset}${yellow}"			# first color
#c1="${reset}${white}"			# second color
#c2="${reset}${bold}${yellow}"		# third color


## OUTPUT

echo "
${nc}       _____      ${nc}${USER}${lc}@${nc}${host}${reset}
${nc}     \-     -/    ${lc}OS:        ${lc}${os}${reset}
${nc}  \_/         \   ${lc}KERNEL:    ${lc}${kernel}${reset}
${nc}  |        ${lc}O O ${nc}|  ${lc}UPTIME:    ${lc}${uptime}${reset}
${nc}  |_  ${lc}<   ${nc})  ${c2}3 ${nc})  ${lc}SHELL:     ${lc}${shell}${reset}
${nc}  / \         /
${nc}     /-_____-\    "

EOF

