#!/bin/sh
#
# ufetch-slackware - tiny system info for slackware

## INFO

# user is already defined
host="$(hostname)"
os="$(cat /etc/slackware-version)"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(ls /var/log/packages | wc -l)"
shell="$(basename "$SHELL")"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE:'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE:'
		WM="${DESKTOP_SESSION}"
	elif [ -f "${HOME}/.xinitrc" ]; then
		envtype='WM:'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM:'
fi

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${magenta}"      # labels
nc="${reset}${bold}${magenta}"      # user and hostname
ic="${reset}${bold}${white}"        # info
c0="${reset}${bold}${magenta}"      # first color

cat <<EOF

${c0}     ________    ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}    /  ______|   ${lc}OS:        ${ic}${os}${reset}
${c0}    | |______    ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}    \\______  \\   ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}     ______| |   ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}  | |________/   ${lc}SHELL:     ${ic}${shell}${reset}
${c0}  |____________  ${lc}${envtype}        ${ic}${WM}${reset}

EOF
