#!/bin/sh
#
# ufetch-aux - tiny system info for a/ux

## INFO

# user is already defined
host=`hostname`
os=`uname -sr`
kernel=`uname -v`
uptime=`uptime | awk '{print $3" "$4}' | tr -d ,`
shell=`basename ${SHELL}`

## DEFINE COLORS

# probably don't change these
bold=`tput bold`
reset=`tput sgr0`

# you can change these
lc="${reset}${bold}"	# labels
nc="${reset}${bold}"	# user and hostname
ic="${reset}"			# info
c0="${reset}"			# first color

## OUTPUT

echo "
${c0}         (/
${c0}    .---__--.   ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}   /         \  ${lc}OS:        ${ic}${os}${reset}
${c0}  |         /   ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}  |         \\_  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}   \         /  ${lc}SHELL:     ${ic}${shell}${reset}
${c0}    \`._.-._.\`
"