#!/bin/sh
#
# ufetch-elementary - tiny system info for elementary os

## INFO

# user is already defined
host="$(hostname)"
os="$(lsb_release -ds)"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(dpkg -l | wc -l)"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE:'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE:'
		WM="${DESKTOP_SESSION}"
	elif [ -f "${HOME}/.xinitrc" ]; then
		envtype='WM:'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM:'
fi

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${green}"		# labels
nc="${reset}${bold}${green}"		# user and hostname
ic="${reset}${bold}${white}"		# info
c0="${reset}${bold}${white}"		# first color
c1="${reset}${white}"		# second color

## OUTPUT

cat <<EOF

${c1}    _______    ${lc}${USER}${ic}@${lc}${host}${reset}
${c1}   / ${c0}____  ${c1}\\   ${lc}OS:        ${ic}${os}${reset}
${c1}  /  ${c0}|  /  /${c1}\\  ${lc}KERNEL:    ${ic}${kernel}${reset}
${c1}  |${c0}__\\ /  /${c1} |  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c1}  \\   ${c0}/__/${c1}  /  ${lc}PACKAGES:  ${ic}${packages}${reset}
${c1}   \\_______/   ${lc}SHELL:     ${ic}${shell}${reset}
${c1}               ${lc}${envtype}        ${ic}${WM}${reset}

EOF
