#!/bin/sh
#
# ufetch-aux - tiny system info for aux

## INFO
# NOTE: you should have bash installed, and you should modify
#       the path appropriately.

# user is already defined
host=`hostname`
os=`uname -sr`
kernel=`uname -v`
uptime=`uptime | awk '{print "Up "$3" "$4}'|tr -d ,`
shell=`basename ${SHELL}`
sar=`sar|grep  Average| awk '{print $1" %usr:"$2" %sys:"$3" %wio:"$4" %idle:"$4}'`

#DEFINE COLORS
bold=`tput bold`
reset=`tput sgr0`


# you can change these
lc="${reset}${bold}"		# labels
nc="${reset}"               # not labels

## OUTPUT
echo "

${nc}         (/     ${nc}${USER}${lc}@${nc}${host}${reset}
${nc}    .---__--.   ${lc}OS:        ${lc}${os}${reset}
${nc}   /         \  ${lc}KERNEL:    ${lc}${kernel}${reset}
${nc}  |         /   ${lc}UPTIME:    ${lc}${uptime}${reset}
${nc}  |         \\_   ${lc}SHELL:     ${lc}${shell}${reset}  
${nc}   \         /  ${lc}SAR:       ${lc}${sar}${reset}
${nc}    \`._.-._.\`    



