#!/bin/sh
#
# ufetch-openbsd - tiny system info for openbsd

## INFO

# user is already defined
host="$(hostname)"
os="$(uname -sr)"
kernel="$(uname -v)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
packages="$(ls -d /var/db/pkg/* | wc -l | sed -e 's/^[ \t]*//')"
shell="$(basename "$SHELL")"

## UI DETECTION

if [ -n "${DE}" ]; then
	ui="${DE}"
	uitype='DE'
elif [ -n "${WM}" ]; then
	ui="${WM}"
	uitype='WM'
elif [ -n "${XDG_CURRENT_DESKTOP}" ]; then
	ui="${XDG_CURRENT_DESKTOP}"
	uitype='DE'
elif [ -n "${DESKTOP_SESSION}" ]; then
	ui="${DESKTOP_SESSION}"
	uitype='DE'
elif [ -f "${HOME}/.xinitrc" ]; then
	ui="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	uitype='WM'
elif [ -f "${HOME}/.xsession" ]; then
	ui="$(tail -n 1 "${HOME}/.xsession" | cut -d ' ' -f 2)"
	uitype='WM'
else
	ui='unknown'
	uitype='UI'
fi

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0 0 0 2>/dev/null)"
	red="$(tput setaf 1 0 0 2>/dev/null)"
	green="$(tput setaf 2 0 0 2>/dev/null)"
	yellow="$(tput setaf 3 0 0 2>/dev/null)"
	blue="$(tput setaf 4 0 0 2>/dev/null)"
	magenta="$(tput setaf 5 0 0 2>/dev/null)"
	cyan="$(tput setaf 6 0 0 2>/dev/null)"
	white="$(tput setaf 7 0 0 2>/dev/null)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${yellow}"       # labels
nc="${reset}${bold}${yellow}"       # user and hostname
ic="${reset}"                       # info
c0="${reset}${yellow}"              # first color
c1="${reset}${white}"               # second color
c2="${reset}${bold}${yellow}"       # third color

## OUTPUT

cat <<EOF

${c0}       _____      ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}     \-     -/    ${lc}OS:        ${ic}${os}${reset}
${c0}  \_/         \   ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}  |        ${c1}O O ${c0}|  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}  |_  ${c2}<   ${c0})  ${c2}3 ${c0})  ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}  / \         /   ${lc}SHELL:     ${ic}${shell}${reset}
${c0}     /-_____-\    ${lc}${uitype}:        ${ic}${ui}${reset}

EOF
