#!/bin/sh
#
# ufetch-netbsd - tiny system info for netbsd

## INFO

# user is already defined
host="$(hostname)"
os="$(uname -sr)"
kernel="$(uname -r)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
packages="$(pkgin list | wc -l | sed -e 's/^[ \t]*//')"
shell="$(basename "$SHELL")"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE:'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE:'
		WM="${DESKTOP_SESSION}"
	elif [ -f "${HOME}/.xinitrc" ]; then
		envtype='WM:'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM:'
fi

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${yellow}"       # labels
nc="${reset}${bold}${yellow}"       # user and hostname
ic="${reset}${bold}${white}"        # info
c0="${reset}${white}"               # first color
c1="${reset}${yellow}"              # second color

## OUTPUT

cat <<EOF

${c0}  \\\\${c1}\`-______,----__    ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}   \\\        ${c1}__,---\`_  ${lc}OS:        ${ic}${os}${reset}
${c0}    \\\       ${c1}\`.____    ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}     \\\\${c1}-______,----\`-  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}      \\\               ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}       \\\              ${lc}SHELL:     ${ic}${shell}${reset}
${c0}        \\\             ${lc}${envtype}        ${ic}${WM}${reset}

EOF
